# Generated by Django 3.2 on 2021-07-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=None)),
                ('contant', models.TextField(max_length=1000)),
                ('auther', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
