# Generated by Django 3.2 on 2021-07-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
