# Generated by Django 3.2.6 on 2021-09-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contant',
            field=models.TextField(max_length=5000),
        ),
    ]
